---
- name: Install Apache
  hosts: server

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

  tasks:
    - name: Check if http present
      yum:
        name: httpd
        state: present

    - name: check if service is running
      service:
        name: httpd
        state: started
        enabled: true